name: build

on:
  release:
    types: [created, edited]

jobs:
  publish:
    name: "Publish crate"
    environment: build
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          export VERSION=`cargo metadata --format-version 1 | jq '.packages[] | select(.name == "cart_container").version' -r`
          echo $GITHUB_REF_NAME $VERSION
          if [[ "$GITHUB_REF_NAME" != "v${VERSION}" ]]; then
            exit 1
          fi
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: '${{ secrets.CARGO_REGISTRY_TOKEN }}'

  build-release-linux:
    name: "Build Release"
    needs: publish
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        rust: [x86_64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{matrix.rust}}
      - run: |
          cargo build --release --target ${{ matrix.rust }}
          cbindgen --config ./cbindgen.toml --crate cart_container --output target/${{ matrix.rust }}/release/cart.h --lang c
          export NAME="cart-${GITHUB_REF_NAME}-${{ matrix.rust }}.tar.gz"
          cd target/${{ matrix.rust }}/release/
          ls .
          tar -czvf $NAME cart.h libcart.so libcart.a
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/release/*.tar.gz"
          tags: true
          draft: true

  build-release-windows:
    name: "Build Release"
    needs: publish
    runs-on: "windows-latest"

    strategy:
      fail-fast: false
      matrix:
        rust: [x86_64-pc-windows-msvc]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{matrix.rust}}
      - run: |
          cargo build --release --target ${{ matrix.rust }}
          cbindgen --config ./cbindgen.toml --crate cart_container --output target/${{ matrix.rust }}/release/cart.h --lang c
          export NAME="cart-${GITHUB_REF_NAME}-${{ matrix.rust }}.tar.gz"
          cd target/${{ matrix.rust }}/release/
          ls .
          tar -czvf $NAME cart.h *.dll *.lib
        shell: bash
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/release/*.tar.gz"
          tags: true
          draft: true